name: Log Analyzer every 2 hours

on:
  schedule:
    - cron: '0 */2 * * *'  # 每兩小時執行一次
  workflow_dispatch:       # 支持手動觸發

jobs:
  analyze:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run log analysis
        run: |
          # 假設 logs 放在 repo 的 logs 資料夾，你要確保這資料夾存在且有檔案
          python log_analyzer.py analyze ./logs

      - name: Upload analysis result JSON
        uses: actions/upload-artifact@v3
        with:
          name: analysis-result
          path: ./logs/search_results.json
