name: Log Analyzer every 2 hours

on:
  schedule:
    - cron: '0 */2 * * *'  # 每兩小時執行一次
  workflow_dispatch:       # 支持手動觸發

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip

      - name: Run log analysis
        id: analyze
        run: |
          python log_analyzer.py logs
        continue-on-error: true  # 讓 workflow 不會因 exit code 1 直接fail

      - name: Get analysis result message
        id: get_msg
        run: |
          # 取出最後一行訊息作為結果
          LAST_LINE=$(tail -n 1 <(echo "${{ steps.analyze.outputs.stdout }}" || cat logs/search_results.json 2>/dev/null))
          echo "msg=$LAST_LINE" >> $GITHUB_OUTPUT

      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.your-company.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Log Analyzer Run Result
          to: your-team@example.com
          from: your-automation@example.com
          content_type: text/html
          body: |
            <h3>Log Analyzer 執行結果通知</h3>
            <p>${{ steps.analyze.outcome == 'success' && '分析成功 ✅' || '分析失敗 ❌' }}</p>
            <pre>${{ steps.analyze.outputs.stdout }}</pre>
